theme: jekyll-theme-minimal
title: Welcome to the victorll998’s homepage!
name: Manuwi
description: Feel free to bookmark this to keep an eye on my project Manuwi's updates
permalink: /:categories/:year/:month/:day/:title:output_ext
