theme: jekyll-theme-minimal
title: Welcome to the Mauwi's homepage!
name: Manuwi
description: Feel free to bookmark this to keep an eye on our project's updates
permalink: /:categories/:year/:month/:day/:title:output_ext
logo: /assets/Screen Shot 2020-11-20 at 10.59.24 pm.png
